# Insert a Number and calc the 
# Multiplication Table

x= int(input('Insert a Number: '))
x1 = (x*1)
x2 = (x*2)
x3 = (x*3)
x4 = (x*4)
x5 = (x*5)
x6 = (x*6)
x7 = (x*7)
x8 = (x*8)
x9 = (x*9)
x10 = (x*10)

print ('-'*12)
print('{} X  1 = {}'.format(x,x1))
print('{} X  2 = {}'.format(x,x2))
print('{} X  3 = {}'.format(x,x3))
print('{} X  4 = {}'.format(x,x4))
print('{} X  5 = {}'.format(x,x5))
print('{} X  6 = {}'.format(x,x6))
print('{} X  7 = {}'.format(x,x7))
print('{} X  8 = {}'.format(x,x8))
print('{} X  9 = {}'.format(x,x9))
print('{} X 10 = {}'.format(x,x10))
print ('-'*12)